name: 'Library change'
description: 'Fix or improve issues with built-in type definitions like `lib.es6.d.ts`, etc.'
body:
  - type: markdown
    attributes:
      value: |
        ### Please fill in each section completely. Thank you!

        Are you here for one of these commonly-requested lib changes?

        * Object.keys - see https://stackoverflow.com/questions/55012174/
        * Array methods - see https://github.com/microsoft/TypeScript/issues/36554
        * `parseInt`, `parseFloat`, `isFinite`, `isNaN`, etc. - see https://github.com/microsoft/TypeScript/issues/4002

        The DOM lib is maintained elsewhere and you can skip a step by filing issues/PRs for the DOM at that repo. See https://github.com/microsoft/TypeScript-DOM-lib-generator
  - type: markdown
    attributes:
      value: |
        If you're missing common new methods like `Array.includes`, you may have a misconfigured project. Try setting `lib: "es2020"` and checking whether the type you want is present. You can diagnose further by running `tsc` with `--listFilesOnly` or `--showConfig`.

        Conversely, if you are seeing built-in methods you expect to *not* see, check your 'lib' setting or review your dependencies for lib/reference directives that might be polluting your global scope. This is common when using the 'node' type library. See https://github.com/microsoft/TypeScript/issues/40184
  - type: input
    id: compilation_target
    attributes:
      label: '⚙ Compilation target'
      description: "What's your compilation target (e.g.: `ES2015`)?"
    validations:
      required: true
  - type: input
    id: current_lib
    attributes:
      label: '⚙ Library'
      description: "What's the current library you're using?"
    validations:
      required: true
  - type: textarea
    id: incorrect_definition
    attributes:
      label: 'Missing / Incorrect Definition'
      description: 'What property, method, function, etc. is missing or incorrect?'
    validations:
      required: true
  - type: textarea
    id: sample_code
    attributes:
      label: 'Sample Code'
      description: "What's some code using this that should work, but doesn't?"
      render: TypeScript
    validations:
      required: true
  - type: textarea
    id: documentation_link
    attributes:
      label: 'Documentation Link'
      description: |
        Link to relevant documentation (e.g. MDN, W3C, ECMAScript Spec) to consult for this property. Note that lib.dom.d.ts intentionally does not include browser-specific extensions or early experimental features.
